# Generated by Django 3.0.3 on 2020-02-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='kart_number',
            new_name='card_number',
        ),
    ]
